### ISSUE TITLE
Last 50 Earnings bug

### ISSUE THREAD

**Issue by aKra-NL** [pablitofernandez/zpoolHashrefineryAhaspoolBTCToFiatConverter#1]
Thanks for your nice little Chrome extension!

Except the 'last 50 earnings' tab will not convert into any FIAT since it gets bugged after enabling the extension.

For example:
![image](https://user-images.githubusercontent.com/20713500/35188254-7630b566-fe32-11e7-8717-db60eb1054da.png)

![image](https://user-images.githubusercontent.com/20713500/35188261-8a873b48-fe32-11e7-8ac3-e6ce3bebc289.png)

**Comment by pablitofernandez** [comment]
I suppose that is from ahashpool and you are right. Last 50 earnings table in ahashpool show results in BTC instead of mBTC. So the fix is straightforward, I will upload a new version to Chrome Extension Library along today.

Thanks for the report @aKra-NL !

**Comment by pablitofernandez** [comment]
New version uploaded to Chrome Extension Gallery, Soon it will be available after Googles revision

**Comment by aKra-NL** [comment]
Nice!
